# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import base_api
from base_api.api.scene_api import SceneApi  # noqa: E501
from base_api.rest import ApiException


class TestSceneApi(unittest.TestCase):
    """SceneApi unit test stubs"""

    def setUp(self):
        self.api = base_api.api.scene_api.SceneApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create(self):
        """Test case for create

        """
        pass

    def test_get(self):
        """Test case for get

        """
        pass

    def test_remove(self):
        """Test case for remove

        """
        pass

    def test_search_by_name(self):
        """Test case for search_by_name

        """
        pass

    def test_update(self):
        """Test case for update

        """
        pass


if __name__ == '__main__':
    unittest.main()
