# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import base_api
from base_api.api.event_api import EventApi  # noqa: E501
from base_api.rest import ApiException


class TestEventApi(unittest.TestCase):
    """EventApi unit test stubs"""

    def setUp(self):
        self.api = base_api.api.event_api.EventApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create(self):
        """Test case for create

        """
        pass

    def test_create_todo(self):
        """Test case for create_todo

        """
        pass

    def test_get(self):
        """Test case for get

        """
        pass

    def test_get_all(self):
        """Test case for get_all

        """
        pass

    def test_get_batch(self):
        """Test case for get_batch

        """
        pass

    def test_get_by_range(self):
        """Test case for get_by_range

        """
        pass

    def test_get_content(self):
        """Test case for get_content

        """
        pass

    def test_get_todos(self):
        """Test case for get_todos

          # noqa: E501
        """
        pass

    def test_remove(self):
        """Test case for remove

        """
        pass

    def test_remove_todo(self):
        """Test case for remove_todo

        """
        pass

    def test_search_by_name(self):
        """Test case for search_by_name

        """
        pass

    def test_search_content(self):
        """Test case for search_content

        """
        pass

    def test_update(self):
        """Test case for update

        """
        pass

    def test_update_content(self):
        """Test case for update_content

        """
        pass

    def test_update_todo(self):
        """Test case for update_todo

        """
        pass


if __name__ == '__main__':
    unittest.main()
