# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import base_api
from base_api.models.create_project_dto import CreateProjectDto  # noqa: E501
from base_api.rest import ApiException

class TestCreateProjectDto(unittest.TestCase):
    """CreateProjectDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateProjectDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateProjectDto`
        """
        model = base_api.models.create_project_dto.CreateProjectDto()  # noqa: E501
        if include_optional :
            return CreateProjectDto(
                name = '', 
                description = ''
            )
        else :
            return CreateProjectDto(
                name = '',
                description = '',
        )
        """

    def testCreateProjectDto(self):
        """Test CreateProjectDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
