# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import base_api
from base_api.models.update_event_dto import UpdateEventDto  # noqa: E501
from base_api.rest import ApiException

class TestUpdateEventDto(unittest.TestCase):
    """UpdateEventDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UpdateEventDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateEventDto`
        """
        model = base_api.models.update_event_dto.UpdateEventDto()  # noqa: E501
        if include_optional :
            return UpdateEventDto(
                done = True, 
                unresolved = [
                    None
                    ], 
                name = '', 
                description = '', 
                color = '', 
                unit = 0, 
                start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else :
            return UpdateEventDto(
        )
        """

    def testUpdateEventDto(self):
        """Test UpdateEventDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
