# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import base_api
from base_api.api.project_api import ProjectApi  # noqa: E501
from base_api.rest import ApiException


class TestProjectApi(unittest.TestCase):
    """ProjectApi unit test stubs"""

    def setUp(self):
        self.api = base_api.api.project_api.ProjectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create(self):
        """Test case for create

          # noqa: E501
        """
        pass

    def test_get(self):
        """Test case for get

          # noqa: E501
        """
        pass

    def test_get_settings(self):
        """Test case for get_settings

          # noqa: E501
        """
        pass

    def test_get_workspace(self):
        """Test case for get_workspace

          # noqa: E501
        """
        pass

    def test_remove(self):
        """Test case for remove

          # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

          # noqa: E501
        """
        pass

    def test_update_settings(self):
        """Test case for update_settings

          # noqa: E501
        """
        pass

    def test_update_workspace(self):
        """Test case for update_workspace

          # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
