# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr

class UpdateProjectDto(BaseModel):
    """
    UpdateProjectDto
    """
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    __properties = ["name", "description"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UpdateProjectDto:
        """Create an instance of UpdateProjectDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UpdateProjectDto:
        """Create an instance of UpdateProjectDto from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return UpdateProjectDto.parse_obj(obj)

        _obj = UpdateProjectDto.parse_obj({
            "name": obj.get("name"),
            "description": obj.get("description")
        })
        return _obj

