# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, StrictFloat, StrictStr, conlist

class CharaEntity(BaseModel):
    """
    CharaEntity
    """
    id: StrictFloat = ...
    name: StrictStr = ...
    alias: conlist(StrictStr) = ...
    description: Optional[StrictStr] = ...
    avatar: Optional[StrictStr] = ...
    deleted: Optional[datetime] = ...
    unit: Optional[StrictFloat] = ...
    start: Optional[datetime] = ...
    end: Optional[datetime] = ...
    project_id: StrictFloat = Field(..., alias="projectId")
    __properties = ["id", "name", "alias", "description", "avatar", "deleted", "unit", "start", "end", "projectId"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CharaEntity:
        """Create an instance of CharaEntity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if description (nullable) is None
        # and __fields_set__ contains the field
        if self.description is None and "description" in self.__fields_set__:
            _dict['description'] = None

        # set to None if avatar (nullable) is None
        # and __fields_set__ contains the field
        if self.avatar is None and "avatar" in self.__fields_set__:
            _dict['avatar'] = None

        # set to None if deleted (nullable) is None
        # and __fields_set__ contains the field
        if self.deleted is None and "deleted" in self.__fields_set__:
            _dict['deleted'] = None

        # set to None if unit (nullable) is None
        # and __fields_set__ contains the field
        if self.unit is None and "unit" in self.__fields_set__:
            _dict['unit'] = None

        # set to None if start (nullable) is None
        # and __fields_set__ contains the field
        if self.start is None and "start" in self.__fields_set__:
            _dict['start'] = None

        # set to None if end (nullable) is None
        # and __fields_set__ contains the field
        if self.end is None and "end" in self.__fields_set__:
            _dict['end'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CharaEntity:
        """Create an instance of CharaEntity from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return CharaEntity.parse_obj(obj)

        _obj = CharaEntity.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "alias": obj.get("alias"),
            "description": obj.get("description"),
            "avatar": obj.get("avatar"),
            "deleted": obj.get("deleted"),
            "unit": obj.get("unit"),
            "start": obj.get("start"),
            "end": obj.get("end"),
            "project_id": obj.get("projectId")
        })
        return _obj

