# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictFloat, StrictStr

class ProjectEntity(BaseModel):
    """
    ProjectEntity
    """
    id: StrictFloat = ...
    serial: StrictFloat = ...
    name: StrictStr = ...
    description: Optional[StrictStr] = ...
    created_at: datetime = Field(..., alias="createdAt")
    updated_at: datetime = Field(..., alias="updatedAt")
    deleted: Optional[datetime] = ...
    __properties = ["id", "serial", "name", "description", "createdAt", "updatedAt", "deleted"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ProjectEntity:
        """Create an instance of ProjectEntity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if description (nullable) is None
        # and __fields_set__ contains the field
        if self.description is None and "description" in self.__fields_set__:
            _dict['description'] = None

        # set to None if deleted (nullable) is None
        # and __fields_set__ contains the field
        if self.deleted is None and "deleted" in self.__fields_set__:
            _dict['deleted'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ProjectEntity:
        """Create an instance of ProjectEntity from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return ProjectEntity.parse_obj(obj)

        _obj = ProjectEntity.parse_obj({
            "id": obj.get("id"),
            "serial": obj.get("serial"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "created_at": obj.get("createdAt"),
            "updated_at": obj.get("updatedAt"),
            "deleted": obj.get("deleted")
        })
        return _obj

