# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import base_api
from base_api.models.workspace_entity import WorkspaceEntity  # noqa: E501
from base_api.rest import ApiException

class TestWorkspaceEntity(unittest.TestCase):
    """WorkspaceEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test WorkspaceEntity
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceEntity`
        """
        model = base_api.models.workspace_entity.WorkspaceEntity()  # noqa: E501
        if include_optional :
            return WorkspaceEntity(
                id = 1.337, 
                origin = '', 
                layout = [
                    None
                    ], 
                lock = True, 
                project_id = 1.337
            )
        else :
            return WorkspaceEntity(
                id = 1.337,
                origin = '',
                layout = [
                    None
                    ],
                lock = True,
                project_id = 1.337,
        )
        """

    def testWorkspaceEntity(self):
        """Test WorkspaceEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
