# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import base_api
from base_api.models.worldview_entity import WorldviewEntity  # noqa: E501
from base_api.rest import ApiException

class TestWorldviewEntity(unittest.TestCase):
    """WorldviewEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test WorldviewEntity
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorldviewEntity`
        """
        model = base_api.models.worldview_entity.WorldviewEntity()  # noqa: E501
        if include_optional :
            return WorldviewEntity(
                path = '', 
                id = 1.337, 
                name = '', 
                description = '', 
                deleted = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                project_id = 1.337, 
                content_id = 1.337
            )
        else :
            return WorldviewEntity(
                path = '',
                id = 1.337,
                name = '',
                description = '',
                deleted = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                project_id = 1.337,
                content_id = 1.337,
        )
        """

    def testWorldviewEntity(self):
        """Test WorldviewEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
