# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import base_api
from base_api.models.update_todo_dto import UpdateTodoDto  # noqa: E501
from base_api.rest import ApiException

class TestUpdateTodoDto(unittest.TestCase):
    """UpdateTodoDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UpdateTodoDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateTodoDto`
        """
        model = base_api.models.update_todo_dto.UpdateTodoDto()  # noqa: E501
        if include_optional :
            return UpdateTodoDto(
                color = '', 
                checked = True
            )
        else :
            return UpdateTodoDto(
        )
        """

    def testUpdateTodoDto(self):
        """Test UpdateTodoDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
